import { FavoriteArtist } from "../../Interface/Store/FavoriteArtist";

export const favArtistData: FavoriteArtist[] = [
  {
    img: "",
    name: "AJR",
    rate: 405,
    listener: 40000,
    topSong: {
      name: "Faded",
      listenCount: "1 643 512 105",
    },
    albums: [
      {
        albumName: "Album 1",
        albumLenght: "15h12min",
        artistName: "AJR",
        listener: 500,
        isTrending: false,
      },
      {
        albumName: "Album 2",
        albumLenght: "15h12min",
        artistName: "AJR",
        listener: 300,
        isTrending: false,
      },
      {
        albumName: "Album 3",
        albumLenght: "15h12min",
        artistName: "AJR",
        listener: 5000,
        isTrending: true,
      },
      {
        albumName: "Album 4",
        albumLenght: "15h12min",
        artistName: "AJR",
        listener: 15000,
        isTrending: true,
      },
    ],
  },
  {
    img: "",
    name: "Adèle",
    rate: 405,
    listener: 40000,
    topSong: {
      name: "Faded",
      listenCount: "1 643 512 105",
    },
    albums: [
      {
        albumName: "Album 1",
        albumLenght: "15h12min",
        artistName: "Adèle",
        listener: 30000,
        isTrending: true,
      },
      {
        albumName: "Album 2",
        albumLenght: "15h12min",
        artistName: "Adèle",
        listener: 750,
        isTrending: false,
      },
      {
        albumName: "Album 3",
        albumLenght: "15h12min",
        artistName: "Adèle",
        listener: 15000,
        isTrending: true,
      },
    ],
  },
  {
    img: "",
    name: "Alan Walker",
    rate: 405,
    listener: 40000,
    topSong: {
      name: "Faded",
      listenCount: "1 643 512 105",
    },
    albums: [
      {
        albumName: "Album 1",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 50000,
        isTrending: true,
      },
      {
        albumName: "Album 2",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 70000,
        isTrending: true,
      },
      {
        albumName: "Album 3",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 6000,
        isTrending: false,
      },
      {
        albumName: "Album 4",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 9000,
        isTrending: false,
      },
      {
        albumName: "Album 5",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 15000,
        isTrending: true,
      },
      {
        albumName: "Album 6",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 975,
        isTrending: false,
      },
      {
        albumName: "Album 7",
        albumLenght: "15h12min",
        artistName: "Alan Walker",
        listener: 25000,
        isTrending: true,
      },
    ],
  },
  {
    img: "",
    name: "Artist name",
    rate: 405,
    listener: 40000,
    topSong: {
      name: "Faded",
      listenCount: "1 643 512 105",
    },
    albums: [
      {
        albumName: "Album 1",
        albumLenght: "15h12min",
        artistName: "Artist name",
        listener: 250,
        isTrending: false,
      },
      {
        albumName: "Album 2",
        albumLenght: "15h12min",
        artistName: "Artist name",
        listener: 850,
        isTrending: false,
      },
      {
        albumName: "Album 3",
        albumLenght: "15h12min",
        artistName: "Artist name",
        listener: 10000,
        isTrending: true,
      },
    ],
  },
];
